### ISSUE TITLE
sudo ./install.sh error: illegal option -n

### ISSUE THREAD

**Issue by Troyciv** [Jonathas-Conceicao/Conjuga-Me-Java#1]
when trying to install with `sudo ./install.sh` it gives me `./install.sh: 3: read: Illegal option -n`

OS: Xubuntu 16.04

**Comment by Jonathas-Conceicao** [comment]
The install script was missing the hashbang at it's first line to specify the /bin/bash. I fix it, it should work properly now.

**Comment by Troyciv** [comment]
thanks for the quick fix

Unfortunately it gives me `mv: cannot move 'conjugame.jar' to '/opt/ConjugaMe/.Jar/conjugame.jar': No such file or directory` now

**Comment by Jonathas-Conceicao** [comment]
That was a missing dot when creating the path for the jar location, sorry for that. I've fixed it.

run `sudo rm -r /opt/ConjugaMe/Jar/` to make sure that the *unnecessary* old folder is removed so it doesn't interfere with the verb's autocomplete. And then run the *install.sh* script.
