### ISSUE TITLE
x rights for installation directory

### ISSUE THREAD

**Issue by Troyciv** [Jonathas-Conceicao/Conjuga-Me-Java#4]
After installation, my /opt/ConjugaMe/ directory was lacking x rights

**Comment by Jonathas-Conceicao** [comment]
Why do you need execute right over there? The ConjugaMe folder is just supposed to hold the Jar serialized objects.

**Comment by Troyciv** [comment]
when I don't give it x rights, I get the following error:

`Error: Unable to access jarfile /opt/ConjugaMe/.Jar/conjugame.jar`

**Comment by Jonathas-Conceicao** [comment]
I had no idea about it, but it seams that when you don't have x rights on the folder you can't access it, so you get the error when trying to read the jar file inside.

I've fixed the install script. It should work fine now.
